/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.conexionmongodb;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.Mongo;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
/**
 *
 * @author David
 */
public class VentanaPeliculas extends javax.swing.JFrame {
    
    /**
     * Creates new form Ventana
     */
    
    List<String> listaGeneros = new ArrayList<>();
    List<String> listaPremios  = new ArrayList<>();
    List<List> listaActores  = new ArrayList<>();
    
    public VentanaPeliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombrePel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBox_generos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTxtResumen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtRecaudación = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxPremios = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTxtNomAct = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonAgrePrem = new javax.swing.JButton();
        jButtonAgreAct = new javax.swing.JButton();
        jButtonAgreGen = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Registro de Peliculas");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(7, 2));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2);
        jPanel1.add(txtNombrePel);

        jLabel3.setText("Género(s)");
        jPanel1.add(jLabel3);

        jBox_generos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comedia", "Drama", "Accion", "Ciencia Ficcion", "Documental", "Terror" }));
        jPanel1.add(jBox_generos);

        jLabel4.setText("Fecha de estreno");
        jPanel1.add(jLabel4);
        jPanel1.add(jDateChooser2);

        jLabel5.setText("Resumen");
        jPanel1.add(jLabel5);
        jPanel1.add(jTxtResumen);

        jLabel6.setText("Recaudación");
        jPanel1.add(jLabel6);
        jPanel1.add(jTxtRecaudación);

        jLabel7.setText("Premios");
        jPanel1.add(jLabel7);

        jComboBoxPremios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Premio Oscar", "Premio Cesar", "Premio Razzie", "Premio Globo de Oro" }));
        jPanel1.add(jComboBoxPremios);

        jLabel8.setText("Actores");
        jPanel1.add(jLabel8);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jTxtNomAct.setText("Nombre");
        jPanel2.add(jTxtNomAct);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principal/Reparto", "Secundario" }));
        jPanel2.add(jComboBoxTipo);

        jPanel1.add(jPanel2);

        jButton1.setText("Guardar Registro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonAgrePrem.setText("Agregar Premio");
        jButtonAgrePrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgrePremActionPerformed(evt);
            }
        });

        jButtonAgreAct.setText("Agregar Actor");
        jButtonAgreAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgreActActionPerformed(evt);
            }
        });

        jButtonAgreGen.setText("Agregar Genero");
        jButtonAgreGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgreGenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAgreGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAgrePrem, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAgreAct, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButtonAgreGen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAgrePrem)
                .addGap(18, 18, 18)
                .addComponent(jButtonAgreAct)
                .addGap(13, 13, 13))
        );

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(301, 301, 301))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(194, 194, 194)
                                .addComponent(jButtonVolver))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jButtonVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PeliculaDAO pelicula = new PeliculaDAO();     
        
        String nom = txtNombrePel.getText();
        Date fecha = jDateChooser2.getDate();
        String res = jTxtResumen.getText();
        String recaudacion = jTxtRecaudación.getText();
        float recFloat = Float.valueOf(recaudacion);
        
        pelicula.insertarPelicula(nom, listaGeneros, fecha, res, listaPremios, recFloat, listaActores);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAgreGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgreGenActionPerformed
        String generos = jBox_generos.getItemAt(jBox_generos.getSelectedIndex());
        listaGeneros.add(generos);
    }//GEN-LAST:event_jButtonAgreGenActionPerformed

    private void jButtonAgrePremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgrePremActionPerformed
        String premios = jComboBoxPremios.getItemAt(jComboBoxPremios.getSelectedIndex());
        listaPremios.add(premios);
    }//GEN-LAST:event_jButtonAgrePremActionPerformed

    private void jButtonAgreActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgreActActionPerformed
        List<String> listInfoAct = new ArrayList<>();
        listInfoAct.add(jTxtNomAct.getText());
        listInfoAct.add(jComboBoxTipo.getItemAt(jComboBoxTipo.getSelectedIndex()));
        listaActores.add(listInfoAct);
    }//GEN-LAST:event_jButtonAgreActActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        VentanaPrincipal vent = new VentanaPrincipal();
        vent.setVisible(true);
        vent.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBox_generos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgreAct;
    private javax.swing.JButton jButtonAgreGen;
    private javax.swing.JButton jButtonAgrePrem;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxPremios;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTxtNomAct;
    private javax.swing.JTextField jTxtRecaudación;
    private javax.swing.JTextField jTxtResumen;
    private javax.swing.JTextField txtNombrePel;
    // End of variables declaration//GEN-END:variables
}
